package opml

import (
	"strings"
	"testing"

	"github.com/71g3pf4c3/charss/internal/urls"
)

func TestParse(t *testing.T) {
	tests := []struct {
		name    string
		input   string
		want    []urls.Feed
		wantErr bool
	}{
		{
			name: "flat feed list",
			input: `<?xml version="1.0" encoding="UTF-8"?>
<opml version="2.0">
  <head><title>subs</title></head>
  <body>
    <outline type="rss" text="Example" title="Example Feed" xmlUrl="https://example.com/feed.xml"/>
    <outline type="rss" text="No title attr" xmlUrl="https://other.com/rss"/>
  </body>
</opml>`,
			want: []urls.Feed{
				{URL: "https://example.com/feed.xml", Title: "Example Feed"},
				{URL: "https://other.com/rss", Title: "No title attr"},
			},
		},
		{
			name: "folder outline becomes tag",
			input: `<opml version="2.0"><body>
  <outline text="Tech" title="Tech">
    <outline type="rss" text="HN" xmlUrl="https://hnrss.org/frontpage"/>
  </outline>
</body></opml>`,
			want: []urls.Feed{
				{URL: "https://hnrss.org/frontpage", Title: "HN", Tags: []string{"Tech"}},
			},
		},
		{
			name: "nested folders accumulate tags, both titles used",
			input: `<opml version="2.0"><body>
  <outline title="News">
    <outline title="Tech">
      <outline type="rss" text="Ars" xmlUrl="https://arstechnica.com/rss"/>
    </outline>
  </outline>
</body></opml>`,
			want: []urls.Feed{
				{URL: "https://arstechnica.com/rss", Title: "Ars", Tags: []string{"News", "Tech"}},
			},
		},
		{
			name: "folder without title falls back to text",
			input: `<opml version="2.0"><body>
  <outline text="Blogs">
    <outline type="rss" text="B" xmlUrl="https://b.com/rss"/>
  </outline>
</body></opml>`,
			want: []urls.Feed{
				{URL: "https://b.com/rss", Title: "B", Tags: []string{"Blogs"}},
			},
		},
		{
			name: "leaf without xmlUrl ignored, containers still recursed",
			input: `<opml version="2.0"><body>
  <outline text="link blog" type="link" url="https://example.com/page"/>
  <outline title="Folder">
    <outline text="bookmark" type="bookmark" url="https://example.com"/>
    <outline type="rss" text="Real" xmlUrl="https://real.com/rss"/>
  </outline>
</body></opml>`,
			want: []urls.Feed{
				{URL: "https://real.com/rss", Title: "Real", Tags: []string{"Folder"}},
			},
		},
		{
			name:  "empty body",
			input: `<opml version="2.0"><body></body></opml>`,
			want:  nil,
		},
		{
			name:    "malformed XML",
			input:   `<opml version="2.0"><body><outline`,
			wantErr: true,
		},
		{
			name:    "wrong root element",
			input:   `<html><body>nope</body></html>`,
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := Parse([]byte(tt.input))
			if (err != nil) != tt.wantErr {
				t.Fatalf("Parse() error = %v, wantErr %v", err, tt.wantErr)
			}
			if tt.wantErr {
				return
			}
			if len(got) != len(tt.want) {
				t.Fatalf("Parse() returned %d feeds, want %d: %+v", len(got), len(tt.want), got)
			}
			for i := range got {
				if got[i].URL != tt.want[i].URL {
					t.Errorf("feed %d URL = %q, want %q", i, got[i].URL, tt.want[i].URL)
				}
				if got[i].Title != tt.want[i].Title {
					t.Errorf("feed %d Title = %q, want %q", i, got[i].Title, tt.want[i].Title)
				}
				if strings.Join(got[i].Tags, "\x00") != strings.Join(tt.want[i].Tags, "\x00") {
					t.Errorf("feed %d Tags = %q, want %q", i, got[i].Tags, tt.want[i].Tags)
				}
				if got[i].Extra != nil {
					t.Errorf("feed %d Extra = %q, want nil", i, got[i].Extra)
				}
			}
		})
	}
}

func TestExportParseRoundtrip(t *testing.T) {
	feeds := []urls.Feed{
		{URL: "https://example.com/feed.xml", Title: "Example Feed"},
		{URL: "https://other.com/rss", Title: "Other", Tags: []string{"tech", "news"}},
		{URL: "https://plain.org/atom", Title: "Plain"},
	}

	data, err := Export(feeds)
	if err != nil {
		t.Fatalf("Export() error: %v", err)
	}
	got, err := Parse(data)
	if err != nil {
		t.Fatalf("Parse(Export()) error: %v", err)
	}
	if len(got) != len(feeds) {
		t.Fatalf("roundtrip returned %d feeds, want %d", len(got), len(feeds))
	}
	for i := range feeds {
		if got[i].URL != feeds[i].URL {
			t.Errorf("feed %d URL = %q, want %q", i, got[i].URL, feeds[i].URL)
		}
		if got[i].Title != feeds[i].Title {
			t.Errorf("feed %d Title = %q, want %q", i, got[i].Title, feeds[i].Title)
		}
		if strings.Join(got[i].Tags, ",") != strings.Join(feeds[i].Tags, ",") {
			t.Errorf("feed %d Tags = %q, want %q", i, got[i].Tags, feeds[i].Tags)
		}
	}
}

func TestExportShape(t *testing.T) {
	data, err := Export([]urls.Feed{{URL: "https://example.com/a", Title: "A & <B>"}})
	if err != nil {
		t.Fatalf("Export() error: %v", err)
	}
	s := string(data)

	for _, want := range []string{
		`<?xml version="1.0" encoding="UTF-8"?>`,
		`<!-- generated by charss`,
		`<opml version="2.0">`,
		`xmlUrl="https://example.com/a"`,
		`type="rss"`,
	} {
		if !strings.Contains(s, want) {
			t.Errorf("export missing %q:\n%s", want, s)
		}
	}
	// XML escaping must be handled by the encoder, not hand-built strings.
	if !strings.Contains(s, "A &amp; &lt;B&gt;") {
		t.Errorf("export does not escape XML special chars:\n%s", s)
	}

	// Empty title falls back to the URL in the text attribute.
	data, err = Export([]urls.Feed{{URL: "https://example.com/a"}})
	if err != nil {
		t.Fatalf("Export() error: %v", err)
	}
	if !strings.Contains(string(data), `text="https://example.com/a"`) {
		t.Errorf("export missing URL fallback for empty title:\n%s", data)
	}
}

func TestParseCategory(t *testing.T) {
	// Roundtripped tags come back via the category attribute.
	feeds := []urls.Feed{{URL: "https://x.com/rss", Title: "X", Tags: []string{"a", "b"}}}
	data, err := Export(feeds)
	if err != nil {
		t.Fatalf("Export() error: %v", err)
	}
	if !strings.Contains(string(data), `category="a,b"`) {
		t.Errorf("export missing category attribute:\n%s", data)
	}
}
