// Package opml implements newsboat-compatible OPML 2.0 import/export of
// feed subscriptions.
//
// On import, folder outlines are flattened: each container's title becomes
// a tag on every feed it contains (nested folders accumulate tags, like
// newsboat does). Outlines without an xmlUrl and without children
// (bookmarks, separators) are ignored.
//
// On export, tags are stored in the OPML 2.0 category attribute
// (comma-separated) so an export/import roundtrip preserves them.
package opml

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"strings"

	"github.com/71g3pf4c3/charss/internal/urls"
)

// opmlDoc mirrors the subset of the OPML 2.0 schema charss cares about.
type opmlDoc struct {
	XMLName xml.Name `xml:"opml"`
	Version string   `xml:"version,attr"`
	Head    *head    `xml:"head,omitempty"`
	Body    body     `xml:"body"`
}

type head struct {
	Title string `xml:"title,omitempty"`
}

type body struct {
	Outlines []outline `xml:"outline"`
}

type outline struct {
	Type     string    `xml:"type,attr,omitempty"`
	Text     string    `xml:"text,attr,omitempty"`
	Title    string    `xml:"title,attr,omitempty"`
	XMLURL   string    `xml:"xmlUrl,attr,omitempty"`
	Category string    `xml:"category,attr,omitempty"`
	Outlines []outline `xml:"outline"`
}

// Parse parses OPML content and returns the contained feeds. Feeds carry
// URL, Title and Tags (folder titles encountered on the way down become
// tags); Extra is left nil.
func Parse(data []byte) ([]urls.Feed, error) {
	var doc opmlDoc
	if err := xml.Unmarshal(data, &doc); err != nil {
		return nil, fmt.Errorf("parsing OPML: %w", err)
	}
	var feeds []urls.Feed
	walk(doc.Body.Outlines, nil, &feeds)
	return feeds, nil
}

// walk collects feeds from outlines, carrying the accumulated folder tags.
func walk(outlines []outline, tags []string, feeds *[]urls.Feed) {
	for _, o := range outlines {
		switch {
		case o.XMLURL != "":
			f := urls.Feed{
				URL:   o.XMLURL,
				Title: firstNonEmpty(o.Title, o.Text),
			}
			f.Tags = make([]string, 0, len(tags))
			f.Tags = append(f.Tags, tags...)
			f.Tags = append(f.Tags, splitCategory(o.Category)...)
			*feeds = append(*feeds, f)
		case len(o.Outlines) > 0:
			// Container outline: recurse, its title becomes a tag for
			// everything inside.
			child := make([]string, 0, len(tags)+1)
			child = append(child, tags...)
			child = append(child, firstNonEmpty(o.Title, o.Text))
			walk(o.Outlines, child, feeds)
		default:
			// Leaf without an xmlUrl: bookmark/separator — ignored.
		}
	}
}

// splitCategory splits an OPML category attribute (comma-separated) into
// plain tags.
func splitCategory(category string) []string {
	if category == "" {
		return nil
	}
	var tags []string
	for _, part := range strings.Split(category, ",") {
		if tag := strings.TrimSpace(part); tag != "" {
			tags = append(tags, tag)
		}
	}
	return tags
}

// Export renders feeds as an indented OPML 2.0 document with a generator
// comment. The text attribute is the feed title (falling back to the URL
// when unset); tags are stored in the category attribute.
func Export(feeds []urls.Feed) ([]byte, error) {
	doc := opmlDoc{
		Version: "2.0",
		Head:    &head{Title: "charss subscriptions"},
	}
	doc.Body.Outlines = make([]outline, 0, len(feeds))
	for _, f := range feeds {
		title := f.Title
		if title == "" {
			title = f.URL
		}
		doc.Body.Outlines = append(doc.Body.Outlines, outline{
			Type:     "rss",
			Text:     title,
			Title:    title,
			XMLURL:   f.URL,
			Category: strings.Join(f.Tags, ","),
		})
	}

	content, err := xml.MarshalIndent(doc, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshaling OPML: %w", err)
	}

	var buf bytes.Buffer
	buf.WriteString(xml.Header)
	buf.WriteString("<!-- generated by charss, a terminal RSS reader -->\n")
	buf.Write(content)
	buf.WriteByte('\n')
	return buf.Bytes(), nil
}

func firstNonEmpty(vals ...string) string {
	for _, s := range vals {
		if s != "" {
			return s
		}
	}
	return ""
}
